## astsa &mdash; applied statistical time series analysis


**more than just data ...**  

... `astsa` is the R package to accompany the [Springer](http://www.springer.com/us/book/9783319524511) text, [Time Series Analysis and Its Applications: With R Examples](http://www.stat.pitt.edu/stoffer/tsa4/)  and the Chapman & Hall text  [Time Series A Data Analysis Approach using R](http://www.stat.pitt.edu/stoffer/tsda/)... both by Shumway and Stoffer. 


We won't always push the latest version of the package to CRAN, but the latest working version of the package will always be at Github.

* See the [News](https://github.com/nickpoison/astsa/blob/master/NEWS.md) for further details about the state of the package and the changelog.

* A demonstration of the capabilities of `astsa` can be found here at
[FUN WITH ASTSA](https://github.com/nickpoison/astsa/blob/master/fun_with_astsa/fun_with_astsa.md)


The Springer text was written under version 1.8 and the Chapman & Hall text was written under version 1.9. Later versions will work for both texts with only some minor changes that won't affect any of the data analysis. 
